# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the source/ directory with Sphinx
sphinx:
   configuration: src/conf.py

# Build formats apart from html
formats:
  - pdf

# Python details
python:
  install:
    - requirements: requirements.txt
